### ISSUE TITLE
How to remove a user created before?

### ISSUE THREAD

**Issue by thanch2n** [GROG/ansible-role-management-user#6]
I tried add [ remove: yes ], but not working.
```
management_user_settings:
  name: mtns
  comment: For maintenance
  shell: '/bin/bash'
  authorized_keys:
    - key: "{{ management_user_key }}"
      exclusive: yes
  sudo:
    hosts: ALL
    as: ALL
    commands: ALL
    nopasswd: yes
  remove: yes
```

**Comment by thanch2n** [comment]
Sorry for my naive question, checked the ansible doc for user module and found state=absent will delete the user.
```
management_user_settings:
  name: mtns
  state: absent
  remove: yes
```
